# Local development environment
# Intention: Run all microservices together with a single command
# Usage: docker-compose up --build

services:
  backend-api:
    build: ./microservices/backend-api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/env_monitor
      - ML_SERVICE_URL=http://ml-service:5001
      - NOTIFICATION_SERVICE_URL=http://notification-service:5002
      - DATA_INGESTION_SERVICE_URL=http://data-ingestion-service:5003
    depends_on:
      - database

  notification-service:
    build: ./microservices/notification-service
    ports:
      - "5002:5002"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TEMP_THRESHOLD=39
      - HUMIDITY_THRESHOLD=55
      - AQ_THRESHOLD=2

  data-ingestion-service:
    build: ./microservices/data-ingestion-service
    ports:
      - "5003:5003"
    environment:
      - BACKEND_API_URL=http://backend-api:5000
      - DATA_DIR=/data
    volumes:
      - ./microservices/database:/data
    depends_on:
      - database
      - backend-api

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=env_monitor
    volumes:
      - ./microservices/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  ml-service:
    build: ./microservices/ml-service
    ports:
      - "5001:5001"
    environment:
      - DATASET_PATH=/data/sensor_data_cleaned.csv
    volumes:
      - ./microservices/database:/data
    depends_on:
      - data-ingestion-service

  # frontend:
  #   build: ./microservices/frontend
  #   ports:
  #     - "3000:3000"
